-- recsys database
DROP TABLE IF EXISTS Ratings CASCADE;
DROP TABLE IF EXISTS Films CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Roles CASCADE;

CREATE TABLE IF NOT EXISTS Roles (
idRole INT AUTO_INCREMENT NOT NULL,
role VARCHAR(100) NOT NULL,
PRIMARY KEY (idRole)
) ENGINE=InnoDB CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS Users (
idUser INT AUTO_INCREMENT NOT NULL,
name VARCHAR(100) NOT NULL,
password VARCHAR(32) NOT NULL,
roleId INT NOT NULL,
UNIQUE (name),
PRIMARY KEY (idUser),
FOREIGN KEY (roleId) REFERENCES Roles(idRole)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=InnoDB CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS Films (
idFilm INT AUTO_INCREMENT NOT NULL,
title VARCHAR(100) NOT NULL,
yr INT NOT NULL,
poster BLOB NOT NULL,
PRIMARY KEY (idFilm)
) ENGINE=InnoDB CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS Ratings (
idRating INT AUTO_INCREMENT NOT NULL,
userId INT NOT NULL,
filmId INT NOT NULL,
rating DOUBLE NOT NULL,
UNIQUE (userId, filmId),
PRIMARY KEY (idRating),
FOREIGN KEY (userId) REFERENCES Users(idUser)
	ON UPDATE CASCADE
	ON DELETE RESTRICT,
FOREIGN KEY (filmId) REFERENCES Films(idFilm)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
) ENGINE=InnoDB CHARACTER SET = UTF8;
